### ISSUE TITLE
simParser crashes on profileSets with stat weights

### ISSUE THREAD

**Issue by seanpeters86** [seanpeters86/bfa-shadow-priest#13]
When running simParser with a json file using profileSets with stat weights you get this error:

```
Traceback (most recent call last):
  File "simParser.py", line 103, in <module>

    main()
  File "simParser.py", line 97, in main
    parses += parse(filename, options.csv, options.hideHeaders, options.hideProfiles, options.hideActors, options.dpsOnly)
  File "simParser.py", line 37, in parse
    ret+= parseProfileSets(filename, isCsv, hideHeaders, hideProfiles, hideActors, dpsOnly)
  File "simParser.py", line 48, in parseProfileSets
    if dpsOnly or 'Int' in profile['scale_factors']:
KeyError: 'scale_factors'
```

Pastebin example json: https://pastebin.com/pH2XgkEd

**Comment by seanpeters86** [comment]
closing due to profileSets not working with weights

**Comment by lgkern** [comment]
Fixed with https://github.com/lgkern/SimAutomation/commit/17a54da19f874e34686651eb25fd030e4950ea16
